version: 2
updates:
  # Root package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    groups:
      production-dependencies:
        patterns:
          - "@openzeppelin/*"
          - "@ensdomains/*"
          - "ethers"
          - "hardhat"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "chai"
          - "mocha"
        update-types:
          - "minor"
          - "patch"
      turbo-dependencies:
        patterns:
          - "turbo"
          - "@turbo/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "chai"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/chai"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  # Contracts package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/contracts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(contracts)"
      prefix-development: "deps-dev(contracts)"
      include: "scope"
    labels:
      - "dependencies"
      - "contracts"
      - "automated"
    groups:
      smart-contract-dependencies:
        patterns:
          - "@openzeppelin/*"
          - "@ensdomains/*"
          - "ethers"
        update-types:
          - "patch"
      hardhat-dependencies:
        patterns:
          - "hardhat*"
          - "@nomicfoundation/*"
          - "@nomiclabs/*"
        update-types:
          - "minor"
          - "patch"
      testing-dependencies:
        patterns:
          - "chai"
          - "mocha"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(web)"
      prefix-development: "deps-dev(web)"
      include: "scope"
    labels:
      - "dependencies"
      - "web"
      - "automated"
    groups:
      react-dependencies:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      wagmi-dependencies:
        patterns:
          - "viem"
          - "wagmi"
          - "@wagmi/*"
        update-types:
          - "minor"
          - "patch"
      build-dependencies:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # UI package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ui)"
      prefix-development: "deps-dev(ui)"
      include: "scope"
    labels:
      - "dependencies"
      - "ui"
      - "automated"
    groups:
      ui-dependencies:
        patterns:
          - "react*"
          - "@types/react*"
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
