saveExact: true
engineStrict: true
enablePrePostScripts: true

packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - unrs-resolver

nodeLinker: hoisted
