packages:
  - apps/*
  - packages/*
enablePrePostScripts: true
engineStrict: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - secp256k1
  - unrs-resolver
  - utf-8-validate
saveExact: true
