packages:
  - apps/*
  - packages/*

enablePrePostScripts: true

engineStrict: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msw
  - secp256k1
  - unrs-resolver
  - utf-8-validate

overrides:
  base-x: '4.0.1'
  brace-expansion: '>=2.0.2'
  cookie: '>=0.7.0'
  debug: '>=3.2.7'
  elliptic: '>=6.6.1'
  eth-gas-reporter: '>=0.2.26'
  flat: '>=5.0.1'
  minimatch: '>=3.0.5'
  pbkdf2: '>=3.1.3'
  request: '>=2.88.2'
  tmp: '>=0.2.4'
  tough-cookie: '>=4.1.3'
  word-wrap: '>=1.2.4'
  ws: '>=7.5.10'

saveExact: true
